# Generated by Django 4.0.4 on 2022-12-09 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0002_votacion_estado_votacion_propietario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='votacion',
            options={'verbose_name': 'Votación', 'verbose_name_plural': 'Votaciones'},
        ),
        migrations.AlterModelOptions(
            name='votante',
            options={'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='votacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='votacion.votacion', verbose_name='Votación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votante',
            name='votacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='votacion.votacion', verbose_name='Votación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votacion',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha de Finalización'),
        ),
    ]
