# Generated by Django 4.0.4 on 2022-12-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0003_alter_candidato_options_alter_votacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.ImageField(null=True, upload_to='candidatos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='ide',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion'),
        ),
    ]
