# Generated by Django 4.0.4 on 2022-12-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0004_alter_candidato_imagen_alter_votante_ide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votos',
            old_name='usuario',
            new_name='votante',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='usuario',
        ),
    ]
