# Generated by Django 4.0.4 on 2022-12-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0005_rename_usuario_votos_votante_remove_votante_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
